# server instance name
host = "ServerName"

# database name
database = "DatabaseName"

# sql query that returns dataset with columns:
# - 'Identifier' string, not null, unique, must use
# - 'HoverInfo' string, nullable, optional
get_symbols_query = """
select
    'lorem'             as Identifier,
    'lorem ipsum dolor' as HoverInfo
"""
